spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/orders?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: service_order
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/orders_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: service_order
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds$->{(id / 10000000).longValue() % 2}
      tables:
        order_tbl:
          actual-data-nodes: ds$->{0..1}.order_tbl_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_tbl_$->{(id / 10000000).longValue() % 2}
          key-generator:
            column: id
            type: SNOWFLAKE