server:
  port: 8080

ignore:
  auth:
    url:
      regex: \\w*
#      regex: \\w*/login

spring:
  application:
    name: nacos-discovery-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dc2615b9-2358-4cd8-baa7-ba152891a673
    sentinel:
      transport:
        dashboard: localhost:8888
