server:
  port: 8081

spring:
  application:
    name: server-2
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dc2615b9-2358-4cd8-baa7-ba152891a673

dubbo:
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    parameters:
      namespace: e182f1bf-90ad-4817-88c8-1278e50d41b0
    address: nacos://localhost:8848
  consumer:
    #启动前不检查服务是否可用
    check: false

management:
  health:
    dubbo:
      status:
        extras: load,threadpool
        defaults: registry,memory,load
  endpoint:
    dubbo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"