seata:
  tx-service-group: account-service
  service:
    vgroup-mapping:
      business-service-group: default
  transport:
    serialization: kryo
  registry:
    file:
      name: file.conf
    type: nacos
    nacos:
      server-addr: ${nacos.server-addr}:${nacos.port}
      namespace: ${nacos.namespace}
  config:
    file:
      name: file.conf
    type: file
    nacos:
      namespace: ${nacos.namespace}
      server-addr: ${nacos.server-addr}:${nacos.port}