server:
  #OS自动分配可用的端口，由于在nacos已经注册了，端口的定义就没有意义了
  port: 0

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dc2615b9-2358-4cd8-baa7-ba152891a673
        metadata:
          name: aabbcc

management:
  endpoints:
    web:
      exposure:
        include: "*"