service:
  dubbo:
    version:
      storage: 0.0.1

logging:
  level:
    io:
      seata: debug

csp:
  sentinel:
    dashboard:
      server: localhost:8888

nacos:
  server-addr: localhost
  port: 8848
  namespace: dc2615b9-2358-4cd8-baa7-ba152891a673

spring:
  profiles:
    active: seata
  application:
    name: dubbo-service-application-storageService
  main:
    allow-bean-definition-overriding: true
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storages
    username: service_storage
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    parameters:
      namespace: ${nacos.namespace}
    address: nacos://${nacos.server-addr}:${nacos.port}
  provider:
    # hash一致策略 (hash环)
    loadbalance: consistenthash