seata:
  enabled: true
  tx-service-group: storage-service
  client:
    rm-report-success-enable: true
    rm-table-meta-check-enable: false
    rm-report-retry-count: 5
    rm-async-commit-buffer-limit: 10000
    rm:
      lock:
        lock-retry-internal: 10
        lock-retry-times: 30
        lock-retry-policy-branch-rollback-on-conflict: true
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 5
    undo:
      undo-data-validation: true
      undo-log-serialization: jackson
      undo-log-table: undo_log
    log:
      exceptionRate: 100
    support:
      spring:
        datasource-autoproxy: true
  service:
    vgroup-mapping:
      business-service-group: default
    enable-degrade: false
    grouplist:
      default: 127.0.0.1:8091
  transport:
    shutdown:
      wait: 3
    thread-factory:
      server-executor-thread-prefix: NettyServerBizHandler
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: kryo
    compressor: none
    enable-client-batch-send-request: true
  registry:
    file:
      name: file.conf
    type: nacos
    nacos:
      server-addr: ${nacos.server-addr}:${nacos.port}
      namespace: ${nacos.namespace.seata}
      cluster: default
  config:
    file:
      name: file.conf
    type: file
    nacos:
      namespace:
      server-addr: ${nacos.server-addr}:${nacos.port}