server:
  port: 8080

logging:
  level:
    io:
      seata: debug

provider:
  service:
    version:
      storage: 0.0.1
      account: 0.0.1
      order: 0.0.1

config:
  server-addr:
    sentinel: localhost
    nacos: localhost
  port:
    sentinel: 8888
    nacos: 8848
  namespace:
    nacos: dc2615b9-2358-4cd8-baa7-ba152891a673

seata:
  tx-service-group: business-service-group
  service:
    vgroup-mapping:
      business-service-group: default
  transport:
    serialization: kryo

spring:
  profiles:
    active: cloud
  application:
    name: business-service
  main:
    allow-bean-definition-overriding: true

dubbo:
  protocol:
    name: dubbo
    serialization: kryo
  registry:
    parameters:
      namespace: ${config.namespace.nacos}
    address: nacos://${config.server-addr.nacos}:${config.port.nacos}

management:
  health:
    dubbo:
      status:
        extras: load,threadpool
        defaults: registry,memory,load
  endpoint:
    dubbo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"