seata:
  tx-service-group: business-service
  service:
    vgroup-mapping:
      business-service-group: default
  transport:
    serialization: kryo
  registry:
    file:
      name: file.conf
    type: nacos
    nacos:
      server-addr: ${config.server-addr.nacos:localhost}:${config.port.nacos:8848}
      namespace: ${config.namespace.nacos:public}
  config:
    file:
      name: file.conf
    type: file
    nacos:
      server-addr: ${config.server-addr.nacos:localhost}:${config.port.nacos:8848}
      namespace: ${config.namespace.nacos:public}