server:
  port: 8080

logging:
  level:
    io:
      seata: debug

provider:
  service:
    version:
      order: 0.0.1
      storage: 0.0.1
      account: 0.0.1

nacos:
  server-addr: localhost
  port: 8848
  namespace: dc2615b9-2358-4cd8-baa7-ba152891a673

spring:
  profiles:
    active: seata
  application:
    name: business-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}:${nacos.port}
        namespace: ${nacos.namespace}

dubbo:
  protocol:
    name: dubbo
    serialization: kryo
  registry:
    parameters:
      namespace: ${nacos.namespace}
    address: nacos://${nacos.server-addr}:${nacos.port}

management:
  health:
    dubbo:
      status:
        extras: load,threadpool
        defaults: registry,memory,load
  endpoint:
    dubbo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"